set define off;

-- fashion

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '몽아미 주 슬리브리스', null, 28000, 10, 100);
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '몽아미 주 슬리브리스' || '%'), 'XL');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '몽아미 주 슬리브리스' || '%'), 'L');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '몽아미 주 슬리브리스' || '%'), 'M');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '몽아미 주 슬리브리스' || '%'), 'SM');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '몽아미 주 슬리브리스' || '%'), '핑크');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '몽아미 주 슬리브리스' || '%'), '옐로우');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '몽아미 주 슬리브리스' || '%'), '스카이블루');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '몽아미 주 슬리브리스' || '%'), 'title', 'monami_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '몽아미 주 슬리브리스' || '%'), 'subTitle', 'monami_subTitle1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '몽아미 주 슬리브리스' || '%'), 'subTitle', 'monami_subTitle2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '몽아미 주 슬리브리스' || '%'), 'content', 'monami_content1.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '하트 여왕 런닝티', null, 27000, 10, 100);
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '하트 여왕 런닝티' || '%'), 'XL');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '하트 여왕 런닝티' || '%'), 'L');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '하트 여왕 런닝티' || '%'), 'M');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '하트 여왕 런닝티' || '%'), 'SM');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '하트 여왕 런닝티' || '%'), '블루');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '하트 여왕 런닝티' || '%'), '레드');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '하트 여왕 런닝티' || '%'), 'title', 'heartqueen_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '하트 여왕 런닝티' || '%'), 'subTitle', 'heartqueen_subTitle1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '하트 여왕 런닝티' || '%'), 'content', 'heartqueen_content1.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '시계 토끼 빕', null, 16000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '시계 토끼 빕' || '%'), 'title', 'clockrebbit_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '시계 토끼 빕' || '%'), 'content', 'clockrebbit_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '시계 토끼 빕' || '%'), 'content', 'clockrebbit_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '밀크 내복티', null, 26000, 0, 100);
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '밀크 내복티' || '%'), 'XL');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '밀크 내복티' || '%'), 'L');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '밀크 내복티' || '%'), 'M');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '밀크 내복티' || '%'), 'SM');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '밀크 내복티' || '%'), 'title', 'milknaebock_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '밀크 내복티' || '%'), 'content', 'milknaebock_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '밀크 내복티' || '%'), 'content', 'milknaebock_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '홀리데이 하트 머플러', null, 11000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '홀리데이 하트 머플러' || '%'), 'title', 'holidayheart_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '홀리데이 하트 머플러' || '%'), 'content', 'holidayheart_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '홀리데이 하트 머플러' || '%'), 'content', 'holidayheart_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '와이키키 블라우스', null, 28000, 0, 100);
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '와이키키 블라우스' || '%'), 'SM');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '와이키키 블라우스' || '%'), 'M');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '와이키키 블라우스' || '%'), 'L');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '와이키키 블라우스' || '%'), 'XL');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '와이키키 블라우스' || '%'), 'title', 'yqqblous_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '와이키키 블라우스' || '%'), 'content', 'yqqblous_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '와이키키 블라우스' || '%'), 'content', 'yqqblous_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '꽃 니트 캐미솔', null, 28000, 0, 100);
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '꽃 니트 캐미솔' || '%'), 'S');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '꽃 니트 캐미솔' || '%'), 'SM');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '꽃 니트 캐미솔' || '%'), 'M');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '꽃 니트 캐미솔' || '%'), 'L');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '꽃 니트 캐미솔' || '%'), 'XL');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '꽃 니트 캐미솔' || '%'), '2XL');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '꽃 니트 캐미솔' || '%'), '데이지');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '꽃 니트 캐미솔' || '%'), '튤립');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '꽃 니트 캐미솔' || '%'), '까멜리아');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '꽃 니트 캐미솔' || '%'), 'title', 'flowerneetcamisol_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '꽃 니트 캐미솔' || '%'), 'subTitle', 'flowerneetcamisol_subTitle1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '꽃 니트 캐미솔' || '%'), 'subTitle', 'flowerneetcamisol_subTitle2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '꽃 니트 캐미솔' || '%'), 'content', 'flowerneetcamisol_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '꽃 니트 캐미솔' || '%'), 'content', 'flowerneetcamisol_content2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '꽃 니트 캐미솔' || '%'), 'content', 'flowerneetcamisol_content3.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '플럼피 피클 슬리브리스 (4 컬러)', '· 국내산 원단으로 제작되어 튼튼한 티셔츠입니다.
· 신축성이 뛰어난 원단으로 활동성이 높습니다.
· 원단 컬러와 잘 어울리는 로고 패치가 달려있습니다.
· 옷의 뒤집어짐을 최소화 하기위해 등 쪽에 다트봉제 처리를 했습니다.
· 네 가지 컬러로 제작되었습니다.', 17900, 0, 100);
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '플럼피 피클 슬리브리스 (4 컬러)' || '%'), '연두피클');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '플럼피 피클 슬리브리스 (4 컬러)' || '%'), '보라피클');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '플럼피 피클 슬리브리스 (4 컬러)' || '%'), '살구피클');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '플럼피 피클 슬리브리스 (4 컬러)' || '%'), '노랑피클');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '플럼피 피클 슬리브리스 (4 컬러)' || '%'), 'title', 'plumpypeekle4color_title.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '플럼피 피클 슬리브리스 (4 컬러)' || '%'), 'content', 'plumpypeekle4color_content1.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '플럼피 피클 슬리브리스 (4 컬러)' || '%'), 'content', 'plumpypeekle4color_content2.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '플럼피 피클 슬리브리스 (4 컬러)' || '%'), 'content', 'plumpypeekle4color_content3.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '키키 점퍼', null, 49000, 0, 100);
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'S');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'SM');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'M');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'L');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'XL');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '2XL');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'kikijumper_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'kikijumper_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'kikijumper_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '더레스트오브라이프 트립 투 베케이션 맨투맨', '· 더레스트오브라이프의 가벼운 쭈리 맨투맨입니다.
· 유연한 스판성으로 입고 벗는 데에 어려움이 없습니다.
· 각 나라를 대표하는 도시가 새겨진 입체 펠트 레터링이 새겨져 귀여운 포인트가 됩니다.
· 함께 매치가 가능한 조거 팬츠와 코디하면 더욱 귀엽습니다.
· 다섯 가지 컬러로 제작되었습니다.', 36000, 0, 100);
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'S');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'SM');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'M');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'L');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'XL');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '2XL');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '하와이');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '칸쿤');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '세부');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'therestoflife_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'therestoflife_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'therestoflife_content2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'therestoflife_content3.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'therestoflife_content4.jpg');

-------- 일요일 추가 작업
INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '모자 장수 카라티', null, 32000, 0, 100);
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'S');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'SM');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'M');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'L');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'XL');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '2XL');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '핑크');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '그린');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'hatsale_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'hatsale_subTitle.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'hatsale_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'hatsale_content2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'hatsale_content3.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '그랑디르 그 해 여름 벌룬 탑', '· 통통 튀는 색감과 꽃무늬의 탑입니다.
· 봄, 여름에 가볍게 착용하기 좋습니다.
· 소형견부터 대형견까지 착용 가능합니다.
· 어깨 밴딩으로 목둘레에 맞추어 착용 가능합니다.
· 네 가지 컬러로 제작되었습니다.', 27500, 0, 100);
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'S');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'SM');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'M');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'L');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'XL');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '2XL');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '주황꽃');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '노랑꽃');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '초록꽃');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '파란꽃');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'grandedgehaesummer_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'grandedgehaesummer_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'grandedgehaesummer_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '오드스튜디오 베이직 러플 티셔츠 (3컬러)', '· 소매에 가득한 러플이 사랑스러움을 더해주는 티셔츠입니다.
· 베이직한 아이템으로 환절기에 적당한 아이템입니다.
· 귀여운 라벨 있어 포인트가 되어줍니다.
· 세 가지 컬러로 제작되었습니다.', 14800, 0, 100);
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'S');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'M');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'L');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'XL');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '핑크');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '옐로우');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '퍼플');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'odstudio_title.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'odstudio_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'odstudio_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '플럼피 이모션 크롭티 (4 컬러)', '· 국내산 원단으로 제작되어 튼튼한 티셔츠입니다.
· 후로피전사 방식으로 보슬보슬한 입체감이 느껴집니다.
· 텐타 가공처리로 세탁 후 변형이 적습니다.
· 옷의 뒤집어짐을 최소화 하기위해 등 쪽에 다트봉제 처리를 했습니다.
· 네 가지 컬러로 제작되었습니다.', 32900, 10, 100);
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'S');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'M');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'L');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'XL');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '2XL');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '부-후 블랙');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '예삐 레드');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '타-다 옐로우');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '냠냠민트');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'plumpyemotion_title.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'plumpyemotion_content1.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'plumpyemotion_content2.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'plumpyemotion_content3.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'plumpyemotion_content4.png');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '또앙 피치 네크리스', '· 고급 부자재를 사용하여 튼튼한 내구성의 목걸이입니다.
· 데일리로 착용이 가능한 포인트 액세서리입니다.
· 다양한 디자인으로 제작되었습니다.
· 체인으로 길이 조절이 가능합니다.', 15000, 5, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'ddoyangpeachnec_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'ddoyangpeachnec_content.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '또앙 하트 네크리스', '· 고급 부자재를 사용하여 튼튼한 내구성의 목걸이입니다.
· 데일리로 착용이 가능한 포인트 액세서리입니다.
· 다양한 디자인으로 제작되었습니다.
· 체인으로 길이 조절이 가능합니다.', 15000, 5, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'ddoyangheartnec_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'ddoyangheartnec_content.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '또앙 레인보우 네크리스', '· 고급 부자재를 사용하여 튼튼한 내구성의 목걸이입니다.
· 데일리로 착용이 가능한 포인트 액세서리입니다.
· 다양한 디자인으로 제작되었습니다.
· 체인으로 길이 조절이 가능합니다.', 15000, 5, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'ddoyangrainbowtnec_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'ddoyangrainbowtnec_content.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '발렌타인 스카프', null, 16000, 15, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'valentainscaf_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'valentainscaf_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'valentainscaf_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '재키 점퍼', null, 49000, 0, 100);
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'SM');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'M');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'L');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'XL');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '2XL');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'jakkyjumper_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'jakkyjumper_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'jakkyjumper_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'toy', '꼬떼 프렌즈 인형', null, 19000, 0, 100);
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '톰(브라운)');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '재키(옐로우)');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '미미(핑크)');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '키키(민트)');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'kkottefriends_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'kkottefriends_content.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'food', '그린쥬쥬 동결건조 홀푸드 바이츠 (살몬블루)', '· 영양소 파괴를 최소화한 동결건조 공법으로 제조된 간식입니다 .
· 연어 100%로 만들어진 간식입니다.
· 채소와 야채 15% 들어가 더욱 건강하게 급여 가능합니다.
· 첨가제, 보존제가 들어가 있지 않습니다.
· 식사 위에 뿌려주거나 칭찬 트릿으로 급여 가능합니다..', 38000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'greenjujubite_title.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'greenjujubite_content.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'food', '포포네 아주칭찬해 (연어고구마)', '· 한 입 크기의 칭찬 트릿입니다.
· 휴대하기 간편한 깔끔한 간식입니다.
· 염분을 제거한 연어에 국내산 고구마를 섞어 만들었습니다.
· 무첨가 무방부제인 건강한 간식입니다.', 6200, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'poponesalmongoguma_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'poponesalmongoguma_subTitle.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'poponesalmongoguma_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'poponesalmongoguma_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'food', '포포네 소떡심', '· 고단백 저지방의 소떡심입니다.
· 오래 씹을 수 있는 천연 개껌입니다.
· 이갈이 시기, 치석제거용 간식으로 좋습니다.
· 무첨가 무방부제인 건강한 간식입니다.', 5500, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'poponesodducksim_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'poponesodducksim_subTitle.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'poponesodducksim_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'poponesodducksim_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'food', '바잇미 덴티스틱 소프트 베지 덴탈껌 30개입', '· 치아가 약한 친구들도 먹을 수 있는 소프트 덴탈스틱입니다.
· 구취 제거에 도움이 되는 성분들로 제작되었습니다.
· 자극적인 인공 향과 색소가 들어가지 않았습니다.
· 두 가지 종류로 제작되었습니다.', 40000, 40, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'bitemedetistick_title.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bitemedetistick_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bitemedetistick_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'food', '포포네 소고기 브라우니 (3pcs SET)', '· 기호성이 높고 지방이 적은 소고기 우둔살을 사용한 브라우니 간식입니다.
· 위장 기능 개선을 돕는 케롭파우더를 골고루 섞어 만들었습니다.
· 부드러운 식감으로 전 연령 급여 가능합니다.
· 무첨가 무방부제인 건강한 간식입니다.
· 50g씩 개별 진공포장됩니다.', 10500, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'poponecowmeatbrownee_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'poponecowmeatbrownee_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'poponecowmeatbrownee_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'food', '동해형씨 원물건조 (열빙어)', '· 국내산, 자연산 원물 그대로 만든 수제 간식입니다.
· 높은 기호성으로 저칼로리입니다.
· 불포화지방과 오메가-3가 함유되어 있습니다.
· 100% 원물 반건조로 인공첨가물이 없습니다.
· 면역력과 성장 발육에 도움을 줍니다.', 13000, 30, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'donghaeyeolbinger_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'donghaeyeolbinger_subTitle1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'donghaeyeolbinger_subTitle2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'donghaeyeolbinger_subTitle3.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'donghaeyeolbinger_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'donghaeyeolbinger_content2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'donghaeyeolbinger_content3.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'donghaeyeolbinger_content4.jpg');

-------- 5월 3일 추가
INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'toy', '꼬떼 프렌즈 쿠션', null, 59000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'ggottefriendcusion_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'ggottefriendcusion_content.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'walking', '[콤보] 아이캔더 스너글 하네스+젠틀리쉬 콤보 (포레스트)', '· 포레스트 하네스, 리드 줄 세트 상품입니다.
· 5가지 레이어로 쿠션감과 착용감이 좋습니다.
· 원터치 버클 착용이 가능합니다.
· 충격 흡수 기능의 탄성 E 밴드로 가슴 부위 압박이 적습니다.
· 두 가지 컬러로 제작되었습니다.', 61000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'icanthesnergle_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'icanthesnergle_subTitle1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'icanthesnergle_subTitle2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'icanthesnergle_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'icanthesnergle_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'walking', '아이캔더 스너글 하네스 (썬셋)', '· 썬셋 아이템과 매칭하여 다양한 스타일링이 가능합니다.
· 5가지 레이어로 쿠션감과 착용감이 좋습니다.
· 원터치 버클 착용이 가능합니다.
· 충격 흡수 기능의 탄성 E 밴드로 가슴 부위 압박이 적습니다.
· 두 가지 컬러로 제작되었습니다.', 38000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'icandorhanesu_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'icandorhanesu_subTitle1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'icandorhanesu_subTitle2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'icandorhanesu_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'icandorhanesu_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'walking', '앤블랭크 조이베어 목줄 (미드나잇 블루)', null, 24000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'anblank_title.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'anblank_subTitle.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'anblank_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'anblank_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'walking', '후르타 캐주얼 칼라 (3컬러)', '· 네오프렌 패드로 내구성이 높아 활동에 이상적인 제품입니다.
· 칼라 스트랩 조절 가능하여 활동하기 편안합니다.
· 야간 가시성을 높여주는 리플렉터 징이 달려있습니다.
· 가벼운 소재와 인체공학적인 디자인으로 제작되었습니다.
· 세 가지 컬러로 제작되었습니다.', 37000, 0, 100);
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '20-30');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '25-35');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '30-40');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '35-45');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '40-50');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '45-55');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '시나몬');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '레이븐');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '링건');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'hurtacasual_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'hurtacasual_content1.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'walking', '베이컨박스 고아웃클럽 산책 안전 패치 3+1 (2개월 분)', '· 벌레가 기피하는 천연 오일이 함유된 패치입니다.
· 편리한 보관과 휴대로 아이들의 산책길을 지켜줍니다.
· 24시간 효과가 지속되는 패치입니다.
· 친환경 콩기름 잉크를 사용하여 환경까지 생각했습니다.
· 반려동물 뿐 만이 아니라 사람도 사용이 가능합니다.', 32000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'bakanbox_title.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakanbox_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakanbox_content2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakanbox_content3.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakanbox_content4.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'walking', '베이컨박스 첨벙첨벙 쿨매트', '· 앞, 뒤 양면이 다른 디자인으로 다양한 분위기로 연출할 수 있는 쿨매트입니다.
· 친환경 폴리머 젤로 곰팡이 방지 원료를 사용하여 더욱 안전하고 위생적으로 사용할 수 있습니다.
· 이중 고주파 마감 처리로 튼튼하며 쿠션감이 있습니다.
· 생활 방수 원단으로 관리가 편리합니다.
· 네 가지 사이즈로 제작되었습니다.', 39000, 0, 100);
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'S');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'M');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'L');
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'XL');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'bakancool_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'bakancool_subTitle1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'bakancool_subTitle2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakancool_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakancool_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'clean', '마이플러피 극세사 한손 타올', '· 한 장 타올 미니 버전으로 출시되었습니다.
· 피부에 자극 없이 물기 제거 가능합니다.
· 한 손에 들어오는 적당한 크기입니다.
· 반복 세탁이 가능하게 튼튼한 바이어스로 마감하였습니다.', 5600, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'myplponetowel_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'myplponetowel_subTitle1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'myplponetowel_subTitle2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'myplponetowel_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'myplponetowel_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'clean', '베이컨박스 워터리스 샴푸', '· 물이 필요 없는 워터리스 샴푸입니다.
· 브러쉬가 달려있어 편리하게 사용할 수 있습니다.
· 무향으로 자극이 없습니다.
· 발바닥, 피부, 항문 어디든 사용 가능합니다.
· EWG GREEN 성분으로 안전합니다.', 18000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'bakanwaterless_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'bakanwaterless_subTitle.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakanwaterless_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakanwaterless_content2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakanwaterless_content3.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'clean', '트리올로지 에브리데이 워크 앤 워시 샴푸', null, 36000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'trioleveryday_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'trioleveryday_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'trioleveryday_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'clean', '이츠독 오가닉 홈케어링 넥카라 (스트라이프)', '· 강아지, 고양이들을 위한 넥 카라입니다.
· 겉커버와 안쪽 방수커버 분리가 가능합니다.
· 오가닉 면으로 피부가 예민한 친구들도 사용 가능합니다.
· 사이즈 조절이 가능한 코드락이 있습니다.
· 다섯 가지 디자인으로 제작되었습니다.', 25000, 5, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'itsdogneckara_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'itsdogneckara_content.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'clean', '리케이 킴라베 327 소형 바리깡 (6컬러)', '· 섬세한 부분을 미용할 수 있는 클리퍼입니다.
· 발 주변, 얼굴 등에 사용이 가능합니다.
· 소음이 적어 아이들의 미용 공포감을 줄여줄 수 있습니다.
· 여섯 가지 컬러로 제작되었습니다.', 79000, 15, 100);
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '블랙');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '화이트');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '핑크');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '퍼플');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '옐로우');
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '그린');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'rekbarikan_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'rekbarikan_content.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'toy', '베이컨박스 문어 소세지 라텍스 토이', '· 삑삑이로 흥미 유발 시켜주는 프렌즈 토이입니다.
· 작은 친구들도 한 입에 갖고 놀 수 있는 토이입니다.
· 무형광 염료와 무독성 천연 라텍스로 안심하고 놀 수 있습니다.
· 바이트 스팟이 있어 다양한 사이즈의 친구들이 사용할 수 있습니다.', 9000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'bakantako_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'bakantako_subTitle1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'bakantako_subTitle2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakantako_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakantako_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'toy', '베이컨박스 왕김밥 노즈워크 토이', '· 노즈워크와 삑삑이가 가능한 토이입니다.
· 시금치로 노즈워크 볼 놀이가 가능합니다.
· 계란말이는 부드러운 원단으로 미니 노즈워크 매트로 사용 가능합니다.
· 새우튀김은 삑삑이가 내장되어 있어 흥미 유도 및 캐치 놀이가 가능합니다.', 22000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'bakankimbab_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'bakankimbab_subTitle1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'bakankimbab_subTitle2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakankimbab_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakankimbab_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'food', '수수펫스튜디오 동결건조 사각사각 (오리/홍삼)', '· 저지방의 오리안심을 넣어 기호성이 높은 동결건조 간식입니다.
· 오리안심, 채소, 과일, 홍삼 등으로만 제작되었습니다.
· 노령견 친구들이나 어린 강아지들에게도 추천합니다.', 13500, 5, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'susupet_title.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'susupet_content.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'food', '포옹 강아지용 베이킷 닭 50g', '· 원물을 통째로 넣어 만들어진 쿠키입니다.
· 화학 보존제가 들어있지 않습니다.
· 휴먼그레이드 재료들을 아낌없이 넣어 제작되었습니다.
· 아이들이 먹기 편안한 크기와 사이즈로 제작되었습니다.
· 다섯 가지 종류로 제작되었습니다.', 6500, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'bakit_title.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakit_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakit_content2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakit_content3.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakit_content4.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'food', '푸디웜 저알러지 기능성 간식 꼬꼬닭안심 (4개 세트)', null, 14000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'foodywarm_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'foodywarm_content.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'food', '복슬강아지 계란 노른자 동결건조 60g', '· 더 영양이 많은 노른자를 건조한 간식입니다.
· 노견들도, 이가 약한 친구들도 먹을 수 있는 간식입니다.
· 비타민D의 보충을 도와줍니다.
· 기억력과 근육 조절에도 도움을 줍니다.', 7000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'boksul_title.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'boksul_content.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'food', '아더마스 사슴 스튜 (180g)', null, 9000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'arthemas_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'arthemas_content1.jpeg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'arthemas_content2.jpeg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'arthemas_content3.jpeg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'food', '브루클린펫코 비스코티 세트 90g (3개)', '· 건강한 맛을 함께 즐길 수 있는 비스코티 간식입니다.
· A세트와 B세트로 나누어져 있습니다.
· 딱딱한 간식이므로 급여 시에는 보호자와 함께 있는 곳에서 급여 부탁드립니다.
· 첨가물 없이 휴먼그레이드 재료들로 제작되었습니다.
· 다양한 재료들이 들어가 아이들의 입맛에 따라 선택의 폭이 넓습니다.', 28000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'bruculo_title.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'bruculo_subTitle.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bruculo_content.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'toy', '베럴즈 스멜즈 토이 민티 (삑삑이)', '· 냄새 분자를 형상화한 형태의 장난감입니다.
· 독특한 삑삑이 소리가 나 아이들의 호기심을 자극합니다.
· 크기가 넉넉하며 견고한 제품으로 터그 놀이를 하기에 좋습니다.
· 스멜즈 토이는 네 종류로 제작되었습니다.', 12800, 10, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'berelsemint_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'berelsemint_subTitle1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'berelsemint_subTitle2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'berelsemint_subTitle3.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'berelsemint_subTitle4.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'berelsemint_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'berelsemint_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'toy', '바잇미 애착 장난감&간식 기프트 세트', '· 선물하기에 좋은 장난감과 간식이 들어있는 기프트 세트입니다.
· 23년 토끼의 해를 상징하는 애착인형이 들어있습니다.
· 두 가지 타입으로 제작되었습니다.', 36000, 15, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'biteme_title.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'biteme_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'biteme_content2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'biteme_content3.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'toy', '베이컨박스 벌크업 캥거루 헌팅 토이', '· 캥거루 주머니로 헌팅과 노즈워크가 가능합니다.
· 장모 보아 원단으로 제작되어 부드러운 촉감을 제공합니다.
· 캥거루 주머니 내 바스락 내장재와 왕 고질 원단으로 마감해 특별한 질감입니다.
· 캥거루와 코카투에 삑삑이가 들어있어 흥미 유발할 수 있습니다.
· 바이트 스팟이 많아 물기 좋습니다.', 25000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'bakanbulkup_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'bakanbulkup_subTitle1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'bakanbulkup_subTitle2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakanbulkup_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'bakanbulkup_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'toy', '오펫 팝콘 노즈워크', '· 다양한 구성의 팝콘 세트 토이 제품입니다.
· 바스락과 삑삑소리가 들어있어 아이들의 흥미를 유발합니다.
· 삑삑이와 노즈워크를 동시에 즐길 수 있습니다.
· 난이도는 1.5단계 정도입니다.', 20000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'popcon_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'popcon_subTitle.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'popcon_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'popcon_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'walking', '스몰스터프 해피 워크 풉 백 (머스타드)', '· 즐거운 산책길을 위한 해피 워크 풉 백입니다.
· 오염 시 세탁이 가능하고, 항상 새것 처럼 사용이 가능합니다.
· 리드줄이나 가방에 걸어 배변봉투를 쉽게 뽑아서 사용할 수 있습니다.
· 네 가지 컬러로 제작되었습니다.', 24000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'smallhappy_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'smallhappy_subTitle.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'smallhappy_content1.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'walking', '어반비스트 배변봉투', '· 18mic의 두께로 쉽게 찢어지거나 냄새가 새지 않습니다.
· 23*33cm의 넉넉한 사이즈로 많은 양을 처리할 수 있습니다.
· 라벤더 향 첨가로 변 냄새를 잡아줍니다.', 12000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'ervanbeast_title.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'ervanbeast_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'ervanbeast_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'clean', '시카로 이지 드라이 타올 (그레이)', '· 흡수력이 뛰어난 천연 대나무 원단으로 제작된 드라이 타올입니다.
· 정전기 방지 원단으로 제작되었습니다.
· 뛰어난 항균기능과 냄새제거 효과가 함께 합니다.
· 원단 무게의 5배까지 흡수가 가능합니다.
· 사용과 휴대가 용이한 디자인입니다.', 59000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'sekaroeasy_title.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'sekaroeasy_content1.jpeg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'sekaroeasy_content2.jpeg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'sekaroeasy_content3.jpeg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'clean', '디고 펫 에스테틱 샴푸 300ml (2개)', '· 안전한 자연 유래 성분으로 만든 샴푸입니다.
· 입자가 부드럽고 풍성한 고밀도 거품으로 세균과 먼지를 탈착시킵니다.
· 피부 진정에 효과적인 병풀 추출물이 함유되어 있습니다.
· 맥주효모가 들어있어 윤기 있는 모질 개선에 도움이 됩니다.
· 자연에서 얻은 세 가지 허브 추출물이 있어 테라피가 가능합니다.', 69600, 20, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'digopetshampoo_title.jpeg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'digopetshampoo_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'digopetshampoo_content2.jpg');

INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'clean', '어노인트 비건 워터리스 멀티클렌져', '· 다양한 유효 보습 성분으로 제작된 멀티 클렌입니다
· 믿을 수 있는 프랑스 이브 비건인증, 독일 더마테스트 등을 통과한 제품입니다.
· 동물 실험을 하지 않은 성분들로 안전하게 제작되었습니다.
· 산책, 여행 시에 간편한 세정에 도움을 줍니다.', 20000, 0, 100);
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'anoint_title.png');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'anoint_content1.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'anoint_content2.jpg');
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'anoint_content3.jpg');





































---- 예제 - 이거 복붙해서 상품이름, 상품가격, 할인율, 옵션이 있다면 사이즈나 색상, 이미지저장이름, 만 바꿔서 사용하면됨
--
--INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
--  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', 'dddd', null, 28000, 0, 100);
--INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
--  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'S');
--INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
--  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'SM');
--INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
--  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'M');
--INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
--  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'L');
--INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
--  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'XL');
--INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
--  VALUES(SIZES_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '2XL');
--INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
--  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '핑크');
--INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
--  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '옐로우');
--INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
--  VALUES (COLOR_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), '스카이블루');
--INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
--  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'dddd_title.jpg');
--INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
--  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'dddd_subTitle1.jpg');
--INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
--  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'dddd_content1.jpg');
--INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
--  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'dddd_content2.jpg');
----
--INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
--  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'toy', 'dddd', null, 22000, 0, 100);
--INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
--  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'title', 'dddd_title.jpg');
--INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
--  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'dddd_subTitle1.jpg');
--INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
--  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'subTitle', 'dddd_subTitle2.jpg');
--INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
--  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'dddd_content1.jpg');
--INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
--  VALUES (IMAGE_SEQ.NEXTVAL, CONCAT('P',LPAD(PRODUCT_SEQ.CURRVAL,4,'0')), 'content', 'dddd_content2.jpg');




commit;
