
-------------------------------- product ----------------------------------------

-- 카테고리별 상품 리스트 -- top-n구문 20개씩만, 페이징, 대표이미지 조인)
SELECT * FROM 
  (SELECT ROWNUM RN, A.* FROM 
    (SELECT P.*, IMAGE FROM PRODUCT P, IMAGE I 
      WHERE P.PRODUCTCODE = I.PRODUCTCODE 
        AND TYPE='title' AND CATEGORY = 'fashion' ORDER BY PRODUCTDATE DESC) A)
  WHERE RN BETWEEN 1 AND 10;
-- 상품 갯수 (카테고리별)
SELECT COUNT(*) FROM PRODUCT WHERE CATEGORY = 'fashion';


-- 상품 상세보기
SELECT * FROM PRODUCT WHERE productCode = 'P0001';
-- 특정 상품의 이미지 리스트 가져오기 (상품리스트에서 해당 상품코드의 이미지 필요함)
SELECT * FROM IMAGE WHERE PRODUCTCODE = 'P0001';
-- 상품 상세보기 (사이즈)
SELECT * FROM SIZES WHERE PRODUCTCODE = 'P0001';
-- 상품 상세보기 (색상)
SELECT * FROM COLOR WHERE PRODUCTCODE = 'P0001';



-- 상품 검색 (이름, )
SELECT * FROM PRODUCT WHERE productName LIKE '%' || TRIM(' 셔츠 ') || '%';

-- 상품 등록
INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSTOCK) 
  VALUES (CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '꽃무늬 티셔츠', '이뻐요', 5000, 15, 50);

-- 상품 사이즈 등록
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, 'P0001', 'XL');

-- 상품 색상 등록
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, 'P0001', '레드');

-- 상품 이미지 등록
INSERT INTO IMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (IMAGE_SEQ.NEXTVAL, 'P0001', 'title', 'flowershirt1.jpg');

-- 상품 수정
UPDATE PRODUCT
		SET CATEGORY = 'food',
    PRODUCTNAME = '맛있는 사료',
    PRODUCTCONTENT = '사료에요 이건',
		productPrice = 34000,
    PRODUCTDISCOUNT = 10,
		productStock = 20
	WHERE productCode = 'P0001';
	
-- 상품 삭제
UPDATE PRODUCT SET PRODUCTUSED = 'N' WHERE PRODUCTCODE = 'P0001';





----------------------------------- CART 관련 ----------------------------------

-- 장바구니에 동일한 상품을 담았는지 확인
SELECT COUNT(*) FROM CART WHERE MEMBERID = 'aaa' AND PRODUCTCODE = 'P0001';

SELECT COUNT(*) FROM CART WHERE MEMBERID = 'aaa' AND PRODUCTCODE = 'P0001' AND SIZENUM = 1;

SELECT COUNT(*) FROM CART WHERE MEMBERID = 'aaa' AND PRODUCTCODE = 'P0001' AND COLORNUM = 2;

SELECT COUNT(*) FROM CART WHERE MEMBERID = 'aaa' AND PRODUCTCODE = 'P0001' AND SIZENUM = 1 AND COLORNUM = 2;



INSERT INTO CART (cartNUM, memberID, productCODE, sizeNUM, colorNUM, QTY, COST)
    VALUES (CART_SEQ.NEXTVAL, 'aaa', 'P0013', null, 12, 1, 1*(SELECT productPRICE- PRODUCTPRICE * (PRODUCTDISCOUNT/100) FROM PRODUCT WHERE productCODE = 'P0002'));

select * from cart;


-- 장바구니 추가
INSERT INTO CART (cartNUM, memberID, productCODE, sizeNUM, colorNUM, QTY, COST)
    VALUES (CART_SEQ.NEXTVAL, 'aaa', 'P0002', 2, 3, 1, (SELECT productPRICE- PRODUCTPRICE * (PRODUCTDISCOUNT/100) FROM PRODUCT WHERE productCODE = 'P0002')*2);
-- 장바구니 목록 (상품명, 상품대표이미지, 상품사이즈, 상품색상, 상품수량, 상품가격)
SELECT A.*
    FROM (SELECT C.*, TYPE, PRODUCTNAME, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSIZE, PRODUCTCOLOR  FROM CART C, IMAGE I, PRODUCT P, SIZES S, COLOR CO 
        WHERE C.PRODUCTCODE = P.PRODUCTCODE AND P.PRODUCTCODE = I.PRODUCTCODE AND C.PRODUCTCODE = S.PRODUCTCODE AND C.PRODUCTCODE = CO.PRODUCTCODE 
                                            AND IMAGENUM= 1 AND C.PRODUCTCODE = 'P0001' AND S.SIZENUM = 1 AND CO.COLORNUM=2 ORDER BY CARTNUM)A;


SELECT P.*, QTY, COST, (SELECT PRODUCTCOLOR FROM COLOR CO WHERE CO.COLORNUM = C.COLORNUM) PRODUCTCOLOR, (SELECT PRODUCTSIZE FROM SIZES S WHERE S.SIZENUM = C.SIZENUM) PRODUCTSIZE, TYPE
    FROM CART C, PRODUCT P, IMAGE I WHERE C.PRODUCTCODE = P.PRODUCTCODE AND C.PRODUCTCODE='P0001' AND P.PRODUCTCODE = I.PRODUCTCODE AND IMAGENUM=1;


SELECT P.*, QTY, COST, (SELECT PRODUCTCOLOR FROM COLOR CO WHERE CO.COLORNUM = C.COLORNUM) PRODUCTCOLOR, (SELECT PRODUCTSIZE FROM SIZES S WHERE S.SIZENUM = C.SIZENUM) PRODUCTSIZE, TYPE
    FROM CART C, PRODUCT P, IMAGE I WHERE C.PRODUCTCODE = P.PRODUCTCODE  AND P.PRODUCTCODE = I.PRODUCTCODE AND IMAGENUM=1 AND  C.PRODUCTCODE = (SELECT PRODUCTCODE FROM CART WHERE PRODUCTCODE='P0001');


-- SELECT C.*, TYPE, PRODUCTNAME, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTSIZE, PRODUCTCOLOR  FROM CART C, IMAGE I, PRODUCT P, SIZES S, COLOR CO 
    -- WHERE C.PRODUCTCODE = P.PRODUCTCODE AND P.PRODUCTCODE = I.PRODUCTCODE AND C.PRODUCTCODE = S.PRODUCTCODE AND C.PRODUCTCODE = CO.PRODUCTCODE AND IMAGENUM= 1 AND C.PRODUCTCODE = 'P0001' AND S.SIZENUM = 1 AND CO.COLORNUM=2;
-- SELECT * FROM CART;

SELECT *
    FROM (SELECT ROWNUM RN, A.*
        FROM (SELECT R.*,(SELECT COUNT(*) FROM GOOD G WHERE G.REVIEWNUM = R.REVIEWNUM) GOODCOUNT FROM REVIEW R ORDER BY GOODCOUNT DESC) A)
    WHERE RN BETWEEN 1 AND 3;


-- 장바구니 전체금액
SELECT SUM(COST) FROM CART;
-- 장바구니 일부 삭제
DELETE FROM CART WHERE CARTNUM = 1;
-- 장바구니 전체 삭제
DELETE FROM CART WHERE MEMBERID = 'aaa';
-- 동일한 상품 담았을 때 수량 수정
INSERT INTO CART (cartNUM, memberID, productCODE, sizeNUM, colorNUM, QTY, COST)
    VALUES (CART_SEQ.NEXTVAL, 'aaa', 'P0001', 1, 2, 2, (SELECT productPRICE- PRODUCTPRICE * (PRODUCTDISCOUNT/100) FROM PRODUCT WHERE productCODE = 'P0001')*2);

-- 장바구니에 동일한 상품을 담았을 때 수량 업데이트
UPDATE CART SET 
    QTY = QTY+1,
    COST = COST + 1*(SELECT PRODUCTPRICE- PRODUCTPRICE * (PRODUCTDISCOUNT/100) FROM PRODUCT WHERE productCODE = 'P0001')
    WHERE MEMBERID = 'aaa' AND PRODUCTCODE = 'P0001' AND SIZENUM = 1 AND COLORNUM = 1;
    
    




--------------------------------- ORDERS ---------------------------------------

-- 카트에 상품 담기전 조회 (이미 담겨져있으면 못 담게 하기)
SELECT * FROM CART WHERE PRODUCTCODE = 'P0001';
-- 카트에 담기 (상품코드, 사이즈, 컬러, 수량, 총가격(서브쿼리에서 상품별 할인 적용))
INSERT INTO CART (CARTNUM, MEMBERID, PRODUCTCODE, SIZENUM, COLORNUM, QTY, COST)
  VALUES (CART_SEQ.NEXTVAL, 'aaa', 'P0001', 1, 2, 3, 3*(SELECT PRODUCTPRICE - PRODUCTPRICE * (PRODUCTDISCOUNT/100) FROM PRODUCT WHERE PRODUCTCODE = 'P0001'));

------ 주문하기 
-- 주문테이블에 데이터 입력
INSERT INTO ORDERS (ORDERNUM, MEMBERID, ORDERNAME, ORDERADDR, ORDERTEL)
  VALUES (CONCAT(TO_CHAR(SYSDATE,'RRMMDD'),LPAD(ORDERS_SEQ.NEXTVAL,4,'0')), 'aaa', '택배받는사람', '택배주소', '010-9999-9999');

-- 주문상세테이블에 입력 (상품코드, 사이즈, 컬러, 수량, 총가격(서브쿼리에서 상품별 할인 적용))
INSERT INTO ORDERDETAIL (ODNO, ORDERNUM, PRODUCTCODE, SIZENUM, COLORNUM, QTY, COST)
  VALUES (ORDERDETAIL_SEQ.NEXTVAL, 
          CONCAT(TO_CHAR(SYSDATE,'RRMMDD'),LPAD(ORDERS_SEQ.CURRVAL,4,'0')), 
         'P0001',1, 2, 3, 3*(SELECT PRODUCTPRICE - PRODUCTPRICE * (PRODUCTDISCOUNT/100) FROM PRODUCT WHERE PRODUCTCODE = 'P0001'));

-- 상품 재고 업데이트 (주문한 수량 만큼만)
UPDATE PRODUCT SET PRODUCTSTOCK = PRODUCTSTOCK - 3 WHERE PRODUCTCODE = 'P0001';

-- 장바구니 비우기 (주문상품만)
DELETE FROM CART WHERE PRODUCTCODE = 'P0001' AND MEMBERID = 'aaa';

-- 'aaa'의 주문내역
SELECT * FROM ORDERS WHERE MEMBERID = 'aaa' ORDER BY ORDERDATE DESC;

--------------------------------- NOTICE ---------------------------------------

-- NOTICE 목록(페이징)
SELECT * FROM
       (SELECT ROWNUM RN, A.* FROM (SELECT * FROM NOTICE ORDER BY NOTICEDATE DESC) A)
    WHERE RN BETWEEN 1 AND 10;

-- NOTICE 전체 글 개수
SELECT COUNT(*) FROM NOTICE;

-- NOTICE 글 상세보기(noticeNum)
SELECT * FROM NOTICE WHERE noticeNum = 1;

-- NOTICE 글 작성
INSERT INTO NOTICE (noticeNum, adminId, noticeTitle, noticeContent)
	VALUES (NOTICE_SEQ.NEXTVAL, 'admin', '제목', '내용');

-- NOTICE 글 수정
UPDATE NOTICE
    SET noticeTitle = '수정제목',
        noticeContent = '수정내용'
    WHERE noticeNum = 1;

-- NOTICE 글 삭제
DELETE FROM NOTICE WHERE noticeNum = 1;


