
-- drop table    -- cascade constraints

DROP TABLE COMMENTS;
DROP TABLE GOOD;
DROP TABLE REVIEW;
DROP TABLE MEMBERGRADE;
DROP TABLE  COUPON;

DROP TABLE ORDERDETAIL;
DROP TABLE ORDERS;
DROP TABLE CART;
DROP TABLE MEMBER;

DROP TABLE PRODUCTIMAGE;
DROP TABLE COLOR;
DROP TABLE SIZES;
DROP TABLE PRODUCT;

-- drop sequence
DROP SEQUENCE COMMENTS_SEQ;
DROP SEQUENCE REVIEW_SEQ;
DROP SEQUENCE COUPON_SEQ;
DROP SEQUENCE ORDERDETAIL_SEQ;
DROP SEQUENCE ORDERS_SEQ;
DROP SEQUENCE CART_SEQ;
DROP SEQUENCE PRODUCTIMAGE_SEQ;
DROP SEQUENCE COLOR_SEQ;
DROP SEQUENCE SIZES_SEQ;
DROP SEQUENCE PRODUCT_SEQ;


-- create table
CREATE TABLE PRODUCT(
  productCODE VARCHAR2(100) PRIMARY KEY,
  CATEGORY VARCHAR2(100) NOT NULL,
  productNAME VARCHAR2(500) NOT NULL,
  productCONTENT VARCHAR2(4000),
  productPRICE NUMBER(10) CHECK(productPRICE > 0) NOT NULL,
  productDISCOUNT NUMBER(4,1),
  productDATE DATE DEFAULT SYSDATE NOT NULL,
  productSTOCK NUMBER(4) CHECK(productSTOCK >= 0) NOT NULL,
  productUSED VARCHAR2(1) NOT NULL
);
CREATE TABLE SIZES(
  sizeNUM NUMBER(4) PRIMARY KEY,
  productCODE VARCHAR2(100) REFERENCES PRODUCT(productCODE) NOT NULL,
  productSIZE VARCHAR2(100) NOT NULL
);
CREATE TABLE COLOR(
  colorNUM NUMBER(4) PRIMARY KEY,
  productCODE VARCHAR2(100) REFERENCES PRODUCT(productCODE) NOT NULL,
  productCOLOR VARCHAR2(100) NOT NULL
);
CREATE TABLE PRODUCTIMAGE(
  imageNUM NUMBER(4) PRIMARY KEY,
  productCODE VARCHAR2(100) REFERENCES PRODUCT(productCODE) NOT NULL,
  TYPE VARCHAR2(100),
  IMAGE VARCHAR2(500)
);

CREATE TABLE MEMBER(
  memberID VARCHAR2(100) PRIMARY KEY,
  memberPW VARCHAR2(100) NOT NULL,
  memberNAME VARCHAR2(100) NOT NULL,
  memberEMAIL VARCHAR2(500) NOT NULL,
  memberTEL VARCHAR2(100),
  memberADDR VARCHAR2(500),
  memberBIRTH DATE,
  memberPOINT NUMBER(10) DEFAULT 0 NOT NULL
);
CREATE TABLE CART(
  cartNUM NUMBER(4) PRIMARY KEY,
  memberID VARCHAR2(100) REFERENCES MEMBER(memberID) NOT NULL,
  productCODE VARCHAR2(100) REFERENCES PRODUCT(productCODE) NOT NULL,
  sizeNUM NUMBER(4) REFERENCES SIZES(sizeNUM),
  colorNUM NUMBER(4) REFERENCES COLOR(colorNUM),
  QTY NUMBER(3) NOT NULL,
  COST NUMBER(10) NOT NULL
);
CREATE TABLE ORDERS(
  orderNUM VARCHAR2(20) PRIMARY KEY,
  memberID VARCHAR2(100) NOT NULL REFERENCES MEMBER(memberID),
  orderDATE DATE DEFAULT SYSDATE NOT NULL,
  orderNAME VARCHAR2(100) NOT NULL,
  orderADDR VARCHAR2(500) NOT NULL,
  orderTEL VARCHAR2(100) NOT NULL
);
CREATE TABLE ORDERDETAIL(
  ODNO NUMBER(4) PRIMARY KEY,
  orderNUM VARCHAR2(100) NOT NULL REFERENCES ORDERS(orderNUM),
  productCODE VARCHAR2(100) NOT NULL REFERENCES PRODUCT(productCODE),
  sizeNUM NUMBER(4) REFERENCES SIZES(sizeNUM),
  colorNUM NUMBER(4) REFERENCES COLOR(colorNUM),
  QTY NUMBER(3) NOT NULL,
  COST NUMBER(10) NOT NULL
);

CREATE TABLE COUPON(
  couponNUM NUMBER(4) PRIMARY KEY,
  memberID VARCHAR2(100) NOT NULL REFERENCES MEMBER(memberID),
  couponNAME VARCHAR2(100),
  couponDISCOUNT NUMBER(8) NOT NULL
);
CREATE TABLE MEMBERGRADE(
  GRADE VARCHAR2(100),
  lowAMOUNT NUMBER(10),
  hiAMOUNT NUMBER(10)
);
CREATE TABLE REVIEW(
  reviewNUM NUMBER(4) PRIMARY KEY,
  meberID VARCHAR2(100) NOT NULL REFERENCES MEMBER(memberID),
  productCODE VARCHAR2(100) NOT NULL REFERENCES PRODUCT(productCODE),
  reviewTITLE VARCHAR2(500) NOT NULL,
  reviewCONTENT VARCHAR2(4000) NOT NULL,
  reviewSCORE NUMBER(2),
  reviewIMAGE VARCHAR2(500),
  reviewDATE DATE DEFAULT SYSDATE NOT NULL,
  reviewIP VARCHAR2(100) NOT NULL
);
CREATE TABLE GOOD(
  reviewNUM NUMBER(4) REFERENCES REVIEW(reviewNUM),
  memberID VARCHAR2(100) REFERENCES MEMBER(memberID),
  CONSTRAINT GOOD_PK PRIMARY KEY(reviewNUM,memberID)
);
CREATE TABLE COMMENTS(
  commentNUM NUMBER(4) PRIMARY KEY,
  memberID VARCHAR2(100) NOT NULL REFERENCES MEMBER(memberID),
  reviewNUM NUMBER(4) NOT NULL REFERENCES REVIEW(reviewNUM),
  commentCONTENT VARCHAR2(4000) NOT NULL,
  commentDATE DATE DEFAULT SYSDATE NOT NULL,
  commentGROUP NUMBER(4) NOT NULL,
  commentSTEP NUMBER(4) NOT NULL,
  commentINDENT NUMBER(4) NOT NULL,
  commentIP VARCHAR2(100) NOT NULL
);

-- CREATE SEQUENCE
CREATE SEQUENCE PRODUCT_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE SEQUENCE SIZES_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE SEQUENCE COLOR_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE SEQUENCE PRODUCTIMAGE_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;

CREATE SEQUENCE CART_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE SEQUENCE ORDERS_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE SEQUENCE ORDERDETAIL_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;

CREATE SEQUENCE COUPON_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE SEQUENCE REVIEW_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE SEQUENCE COMMENTS_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;


