
-- PRODUCT
INSERT INTO PRODUCT (PRODUCTCODE, CATEGORY, PRODUCTNAME, PRODUCTCONTENT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTDATE, PRODUCTSTOCK, PRODUCTUSED) 
  VALUES ( CONCAT('P',LPAD(PRODUCT_SEQ.NEXTVAL,4,'0')), 'fashion', '럭셔리티셔츠', '멋있어요', 3000, 5, SYSDATE, 10, 'Y');

SELECT * FROM PRODUCT;
-- SIZES
INSERT INTO SIZES(SIZENUM, PRODUCTCODE, PRODUCTSIZE) 
  VALUES(SIZES_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '럭셔리티셔츠' || '%'), 'XL');

SELECT * FROM SIZES;
-- COLOR
INSERT INTO COLOR (COLORNUM, PRODUCTCODE, PRODUCTCOLOR) 
  VALUES (COLOR_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '럭셔리티셔츠' || '%'), '레드');

SELECT * FROM COLOR;
-- PRODUCTIMAGE
INSERT INTO PRODUCTIMAGE (IMAGENUM, PRODUCTCODE, TYPE, IMAGE)
  VALUES (PRODUCTIMAGE_SEQ.NEXTVAL, (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '럭셔리티셔츠' || '%'), 'title', 'tshirt.jpg');

SELECT * FROM PRODUCTIMAGE;
-- MEMBER
INSERT INTO MEMBER (MEMBERID, MEMBERPW, MEMBERNAME, MEMBEREMAIL, MEMBERTEL, MEMBERADDR, MEMBERBIRTH, MEMBERPOINT)
  VALUES ('aaa', '1', '신치윤', 'shwoo1103@gmail.com', '010-6344-4081', '인천시 남동구 만수동 1081-3', '93-11-03', 0);

SELECT * FROM MEMBER;
-- CART
INSERT INTO CART (CARTNUM, MEMBERID, PRODUCTCODE, SIZENUM, COLORNUM, QTY, COST)
  VALUES (CART_SEQ.NEXTVAL, 'aaa', 
      (SELECT PRODUCTCODE FROM PRODUCT WHERE PRODUCTNAME LIKE '%' || '럭셔리티셔츠' || '%'), 
      1, 2, 1, 1*(SELECT PRODUCTPRICE FROM PRODUCT WHERE PRODUCTCODE = 'P0001'));

-- ORDERS
  --CONCAT(TO_CHAR(SYSDATE,'RRMMDD'),LPAD(OSEQ.NEXTVAL,3,'0'))


-- ORDERDETAIL

-- COUPON

-- MEMBERGRADE

-- REVIEW

-- GOOD

-- COMMENTS








